ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'CSV_IMPORT_STARTED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'CSV_IMPORT_COMPLETED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'CSV_IMPORT_FAILED';
