ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'USER_LOCKED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'USER_UNLOCKED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'USER_REACTIVATED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'USER_ROLES_UPDATED';
