ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'CATEGORY_UPDATED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'MANUFACTURER_UPDATED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'LOCATION_UPDATED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'ASSET_ARCHIVED';
