ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'WEB_SESSION_CREATED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'WEB_SESSION_LOGGED_OUT';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'WEB_SESSION_EXPIRED';
