ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'CATEGORY_CREATED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'MANUFACTURER_CREATED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'LOCATION_CREATED';
