package com.assetdock.api.audit.domain;

public enum AuditEventType {
	LOGIN_SUCCESS,
	LOGIN_FAILURE,
	USER_CREATED,
	USER_DISABLED,
	USER_LOCKED,
	USER_UNLOCKED,
	USER_REACTIVATED,
	USER_UPDATED,
	USER_ROLES_UPDATED,
	CATEGORY_CREATED,
	MANUFACTURER_CREATED,
	LOCATION_CREATED,
	ASSET_CREATED,
	ASSET_UPDATED,
	ASSET_ASSIGNED,
	ASSET_UNASSIGNED,
	CSV_IMPORT_STARTED,
	CSV_IMPORT_COMPLETED,
	CSV_IMPORT_FAILED
}
